import js from '@eslint/js'
import globals from 'globals'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

export default [
  {
    // Ignore built output and all legacy pre-migration components.
    // Legacy files are not touched per CLAUDE.md — they are excluded from linting.
    ignores: [
      'dist',
      'src/components/auth/**',
      'src/components/cash/**',
      'src/components/clients/**',
      'src/components/common/**',
      'src/components/customer/**',
      'src/components/customers/**',
      'src/components/dashboard/**',
      'src/components/events/**',
      'src/components/expenses/**',
      'src/components/financial/**',
      'src/components/import-export/**',
      'src/components/inventory/**',
      'src/components/invoice/**',
      'src/components/layout/**',
      'src/components/notifications/**',
      'src/components/orders/**',
      'src/components/pos/**',
      'src/components/printing/**',
      'src/components/quickrepairs/**',
      'src/components/reports/**',
      'src/components/security/**',
      'src/components/services/**',
      'src/components/settings/**',
      'src/components/shared/**',
      'src/components/technicians/**',
      'src/components/tenant/**',
      'src/components/timetracking/**',
      'src/components/unlocks/**',
      'src/components/users/**',
      'src/components/utils/**',
      'src/components/widgets/**',
      'src/components/_archive/**',
      'src/components/wizard/**',
      'src/components/workorder/**',
      'src/components/desktop/**',
      'src/pages/_archive/**',
      'src/components/ui/**',
      'src/components/api/**',
      'src/components/Auth.jsx',
      'src/components/UserNotRegisteredError.jsx',
      'src/api/**',
      'src/Entities/**',
      'src/types/**',
      'src/pages/Activate.jsx',
      'src/pages/Clients.jsx',
      'src/pages/Dashboard.jsx',
      'src/pages/Home.jsx',
      'src/pages/index.jsx',
      'src/pages/InitialSetup.jsx',
      'src/pages/Layout.jsx',
      'src/pages/Notifications.jsx',
      'src/pages/OnboardingMojo.jsx',
      'src/pages/Reports.jsx',
      'src/pages/Settings.jsx',
      'src/pages/SettingsGeneral.jsx',
      'src/pages/SettingsMobile.jsx',
      'src/pages/Setup.jsx',
      'src/pages/TenantManagement.jsx',
      'src/pages/UsersManagement.jsx',
      'src/pages/VerifySetup.jsx',
      'tailwind.config.js',
      'vite.config.js',
      'postcss.config.js',
    ],
  },
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    settings: { react: { version: '18.3' } },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      'react/jsx-no-target-blank': 'off',
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
    },
  },
]
