/**
 * Spark Mojo SM DocType TypeScript interfaces
 *
 * Generated from Frappe POC VPS schema (site "frontend").
 * frappe-types is installed on the VPS but cannot generate types for
 * custom DocTypes — only app-bundled ones. These were generated by
 * extracting field metadata via bench execute and converting to TS interfaces.
 *
 * When SM DocTypes move into the sm_connectors app, frappe-types can
 * auto-generate these via: bench --site frontend generate-types-for-doctype
 */

export type { SMClient } from "./SMClient";
export type { SMOnboardingItem } from "./SMOnboardingItem";
export type { SMOutreachAttempt } from "./SMOutreachAttempt";
export type { SMInvoice } from "./SMInvoice";
